import { createHmac, timingSafeEqual } from 'node:crypto';
function env(name) { return String(globalThis.Netlify?.env?.get(name) || process.env[name] || '').trim(); }
function reply(statusCode, body, extra = {}) { return { statusCode, headers: {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extra}, body:JSON.stringify(body) }; }
function site() { try { const u = new URL(env('PUBLIC_SITE_URL')); return u.protocol === 'https:' ? u : null; } catch { return null; } }
function missing() { const names=['PUBLIC_SITE_URL','TURNSTILE_SITE_KEY','TURNSTILE_SECRET_KEY','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN','SESSION_SIGNING_SECRET']; const absent=names.filter(n=>!env(n)); if (!site() && !absent.includes('PUBLIC_SITE_URL')) absent.push('PUBLIC_SITE_URL'); if(env('SESSION_SIGNING_SECRET').length<32 && !absent.includes('SESSION_SIGNING_SECRET')) absent.push('SESSION_SIGNING_SECRET'); try {if(new URL(env("UPSTASH_REDIS_REST_URL")).protocol!=="https:" && !absent.includes("UPSTASH_REDIS_REST_URL"))absent.push("UPSTASH_REDIS_REST_URL");}catch{if(!absent.includes("UPSTASH_REDIS_REST_URL"))absent.push("UPSTASH_REDIS_REST_URL");} return absent; }
async function timedJson(url, options={}, ms=4000) { const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),ms);try { const res=await fetch(url,{...options,signal:ctrl.signal}); if(!res.ok) throw new Error('Upstream unavailable');return await res.json(); }finally{clearTimeout(timer);} }
async function redis(command) { const url=new URL(env('UPSTASH_REDIS_REST_URL'));if(url.protocol!=='https:')throw new Error('Invalid Redis URL'); const result=await timedJson(url.href,{method:'POST',headers:{authorization:`Bearer ${env('UPSTASH_REDIS_REST_TOKEN')}`,'content-type':'application/json'},body:JSON.stringify(command)});if(result.error)throw new Error('Redis command failed');return result.result; }
function limitValue(name,fallback,max) { const n=Number(env(name));return Number.isInteger(n)&&n>0?Math.min(n,max):fallback; }
function ip(event) { return event.trustedIp || ''; }
function digest(value) { return createHmac('sha256',env('SESSION_SIGNING_SECRET')).update(value).digest('hex'); }
function validSession(event) { const cookie=String(event.headers?.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('pulpit_session=')); if(!cookie || !ip(event))return false;const raw=cookie.slice(15);const parts=raw.split('.');if(parts.length!==2)return false;const [payload,signature]=parts;let data;try{data=JSON.parse(Buffer.from(payload,'base64url').toString());}catch{return false;}if(!data || typeof data !== "object" || !Number.isFinite(data.exp)||data.exp<Date.now()||data.exp>Date.now()+16*60*1000||data.ip!==digest(ip(event)))return false;const a=Buffer.from(signature);const b=Buffer.from(digest(payload));return a.length===b.length&&timingSafeEqual(a,b); }
function issueSession(event) { const payload=Buffer.from(JSON.stringify({exp:Date.now()+15*60*1000,ip:digest(ip(event))})).toString('base64url');return `pulpit_session=${payload}.${digest(payload)}; Path=/; Max-Age=900; HttpOnly; Secure; SameSite=Strict`; }
// One atomic operation enforces client and shared daily budgets across function instances.
async function quota(event, cost=1, session=false) { const now=Date.now();const hash=digest(ip(event));const bucket=Math.floor(now/60000);const day=Math.floor(now/86400000);const script="local a=tonumber(redis.call('GET',KEYS[1]) or '0'); local b=tonumber(redis.call('GET',KEYS[2]) or '0'); if a>=tonumber(ARGV[1]) or b+tonumber(ARGV[3])>tonumber(ARGV[2]) then return 0 end; redis.call('INCR',KEYS[1]); redis.call('EXPIRE',KEYS[1],120); redis.call('INCRBY',KEYS[2],ARGV[3]); redis.call('EXPIRE',KEYS[2],172800); return 1";
 const client=limitValue('PULPIT_REQUESTS_PER_MINUTE',session?6:10,60);const budget=session?1000:limitValue('PULPIT_DAILY_BUDGET',100,10000);
 return Number(await redis(['EVAL',script,'2',`pulpit:${session?'session':'ai'}:${hash}:${bucket}`,`pulpit:${session?'sessions':'budget'}:${day}`,String(client),String(budget),String(cost)]))===1; }
async function protect(event,{cost=1,session=false,maxBytes=50000}={}) { const h=event.headers||{};if(event.isBase64Encoded || Buffer.byteLength(event.body||'','utf8')>maxBytes)return reply(413,{error:'Request too large.'}); if(event.httpMethod==='POST' && !/^application\/json(?:;|$)/i.test(h['content-type']||''))return reply(415,{error:'Use a JSON request.'});if(missing().length)return reply(503,{error:'Public AI access is not configured yet.'});if(!ip(event))return reply(503,{error:'Client verification is unavailable.'});if(h.origin && h.origin!==site().origin)return reply(403,{error:'Request origin is not allowed.'});if(!session && !validSession(event))return reply(401,{error:'Please complete the human verification.',code:'verification_required'});try{if(!await quota(event,cost,session))return reply(429,{error:'Usage limit reached. Please try later.'},{'retry-after':'60'});}catch{return reply(503,{error:'Access protection is temporarily unavailable. Please try later.'});}return null; }
async function toEvent(req,context,max=50000) { let body='';if(req.body){const reader=req.body.getReader();let size=0;const chunks=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error('body_limit');}chunks.push(Buffer.from(value));}body=Buffer.concat(chunks).toString('utf8');}return {httpMethod:req.method,headers:Object.fromEntries(req.headers),body,isBase64Encoded:false,trustedIp:context?.ip,queryStringParameters:Object.fromEntries(new URL(req.url).searchParams)}; }
function web(result) { return new Response([204,304].includes(result.statusCode) ? null : result.isBase64Encoded ? Buffer.from(result.body, "base64") : result.body,{status:result.statusCode,headers:{"cache-control":"no-store","x-content-type-options":"nosniff",...result.headers}}); }
export {env,reply,site,missing,timedJson,redis,protect,validSession,issueSession,toEvent,web};
export default {env,reply,site,missing,timedJson,redis,protect,validSession,issueSession,toEvent,web};
